//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sucursal
    {
        public int IdSucursal { get; set; }
        public string NombreSucursal { get; set; }
        public string LogoSucursal { get; set; }
        public string DireccionSucursal { get; set; }
        public int TelefonoSucursal { get; set; }
        public string DescripcionSucursal { get; set; }
    }
}
